### ISSUE TITLE
TDSR fails to start on Python 3.14

### ISSUE THREAD

**Issue by vadimkholodilo** [tspivey/tdsr#48]
When starting TDSR, I get the following error: "from importlib.abc import Traversable
ImportError: cannot import name 'Traversable'".

However, if I change Python version to 3.11, it starts normally.
Why is it important to fix this issue?
If users install Python from Homebrew, they would get Python 3.14 by default and changing. UV would use this version, because in the pyproject.yaml, the requirement for Python is greater than 3.9.
A temperary workaround is to pin Python 3.11 globally in uv, install TDSR, and pin the latest version or to specify an exact version number in pyproject.yaml.

I can submit a PR to make TDSR working on 3.14, if that's ok with everyone.
